# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'voter' do

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Firestore'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for voter

  target 'voterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'voterUITests' do
    # Pods for testing
  end

end
